### PR TITLE
Updated httpd to 2.4.26 and openssl to 1.0.2l-1~bpo8+1

### PR DESCRIPTION
**Pull request by marvec**

### CODE REVIEW

**Comment by marvec** [comment]
Suffers from https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220160

**Comment by csandanov** [comment]
It seems that starting from 2.4.26 there's a problem with openssl/libressl versions, [this patch](https://git.alpinelinux.org/cgit/aports/plain/main/apache2/libressl.patch) used by alpine team for their [apache 2.4.27](https://git.alpinelinux.org/cgit/aports/tree/main/apache2/APKBUILD) package helps.

**Comment by tianon** [comment]
They don't mention where their patch came from, but it looks similar to the code being discussed in https://bz.apache.org/bugzilla/show_bug.cgi?id=61184 by the upstream Apache maintainers (who have expressed concerns with it in that thread).

**Comment by tianon** [comment]
This has been updated since. :+1: :heart:  Thanks!

**Pull request closed without merging**
