### PR TITLE
Update to 2.4.26

### LINKED ISSUE #56: Update httpd:2.4 to version 2.4.26
httpd version 2.4.26 was released two days ago, fixing 5 Important vulnerabilities: https://httpd.apache.org/security/vulnerabilities_24.html

### PR DESCRIPTION
**Pull request by tianon**
Closes #56

### CODE REVIEW

**Comment by tianon** [comment]
Arg, looks like Alpine fails to build. :disappointed:

**Comment by tianon** [comment]
Looks like it's due to LibreSSL, but we can't switch back to OpenSSL due to other dependencies of httpd. :disappointed:

Probably going to require some kind of patch to upstream's code. :confused:

**Comment by tianon** [comment]
The code we're currently failing on is: https://github.com/apache/httpd/blob/2.4.26/support/ab.c#L2517-L2520

**Comment by tianon** [comment]
(If we manage to get past/around that failure, we might run into https://github.com/apache/httpd/blob/2.4.26/modules/ssl/ssl_engine_init.c#L629-L644 too)

**Comment by tianon** [comment]
```c
#if OPENSSL_VERSION_NUMBER >= 0x10100000L
    SSL_CTX_set_max_proto_version(ssl_ctx, max_prot);
    SSL_CTX_set_min_proto_version(ssl_ctx, min_prot);
#endif
```
The `#if` here _seems_ to imply that these function calls aren't actually required, but that doesn't seem right, especially since these lines were all added in 2.4.26, which is a security fix update. :disappointed:

**Comment by tianon** [comment]
See also https://github.com/apache/httpd/compare/2.4.25...2.4.26#diff-64b94abffd4338fbfa6d4bd8e8fab75cR2517 (which is a big diff, so might not load properly)

**Comment by wcgcoder** [comment]
While alpine is being fixed, could we get a non-alpine release of 2.4.26, possibly?
Thanks so much!

**Comment by tianon** [comment]
Yeah, I guess we have to -- the upstream maintainers/contributors don't seem too keen to prioritize https://bz.apache.org/bugzilla/show_bug.cgi?id=61184. :disappointed:

I've adjusted this to only update Debian (including the necessary changes to `generate-stackbrew-library.sh` for that to actually work properly).

**Pull request merged**
