### PR TITLE
add apr-util-ldap package to httpd:2.4-alpine (for LDAP authentication)

### PR DESCRIPTION
**Pull request by Florent38**
Closes https://github.com/docker-library/httpd/issues/64

### CODE REVIEW

**Comment by tianon** [comment]
Given that the size difference is essentially nothing, I'm +1 (~87.1MB vs ~87.1MB). :+1:

@yosifkit ?

**Comment by tianon** [comment]
Oh, the size is no different because the package gets removed further down -- this doesn't actually include the package. :sweat_smile:

**Comment by Florent38** [comment]
Sorry about that. New commit will fix this, I added the apr-util-ldap package in runDeps instead of buildDeps.

Size difference is minimal : 87104306 (with) vs 87093909 (without)

Package is correctly installed : 
```
# apk info apr-util-ldap
apr-util-ldap-1.5.4-r3 description:
The Apache Portable Runtime Utility Library - LDAP driver

apr-util-ldap-1.5.4-r3 webpage:
http://apr.apache.org/

apr-util-ldap-1.5.4-r3 installed size:
28672
```

**Comment by yosifkit** [comment]
Given that this is basically https://github.com/docker-library/httpd/pull/19. :+1:

Should we also apply it to 2.2?

**Pull request merged**
