### PR TITLE
Make apxs work again

### PR DESCRIPTION
**Pull request by palfrey**
This mostly fixes the items in #4, or at least makes it possible to build mod_wsgi again...

### CODE REVIEW

**Comment by yosifkit** [comment]
Since we are keeping these `-dev` libraries, can we put them up with the earlier dependencies near line 15 so we can share the layer between `2.2` and `2.4`?

**Comment by yosifkit** [comment]
Thanks for your contribution! :cake:

**Comment by palfrey** [comment]
@yosifkit Done. Also nicely simplifies the diff :)

**Comment by yosifkit** [comment]
`libc6-dev` is not needed? Or maybe I am missing something.

**Comment by palfrey** [comment]
libc6-dev is an indirect dependency of both libapr1-dev and libaprutil1-dev, so we don't need to explictly install it.

**Comment by yosifkit** [comment]
Oh, nice! LGTM

cc @tianon

**Comment by tianon** [comment]
LGTM, thanks!

**Pull request merged**
