### PR TITLE
Upgrade alpine to v3.5

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by tianon** [comment]
I'm +1 on the change, but only after the Alpine image maintainers update `latest` to point to `3.5` (see https://github.com/docker-library/official-images/pull/2489#discussion_r93885746).

**Comment by PeterDaveHello** [comment]
@tianon now the `alpine:latest` is same as `alpine:3.5` :)

**Comment by tianon** [comment]
```console
+ apk add --no-cache --virtual .build-deps apr-dev apr-util-dev perl ca-certificates gcc gnupg libc-dev libxml2-dev lua-dev make openssl openssl-dev pcre-dev tar zlib-dev
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  libressl-dev-2.4.4-r0:
    conflicts:
               openssl-dev-1.0.2j-r2[pc:libcrypto=2.4.4]
               openssl-dev-1.0.2j-r2[pc:libssl=2.4.4]
               openssl-dev-1.0.2j-r2[pc:openssl=2.4.4]
    satisfies:
               postgresql-dev-9.6.1-r0[libressl-dev]
               openldap-dev-2.4.44-r3[libressl-dev]
  openssl-dev-1.0.2j-r2:
    conflicts:
               libressl-dev-2.4.4-r0[pc:libcrypto=1.0.2j]
               libressl-dev-2.4.4-r0[pc:libssl=1.0.2j]
               libressl-dev-2.4.4-r0[pc:openssl=1.0.2j]
  .build-deps-0:
    masked in: cache
    satisfies: world[.build-deps]
```

**Comment by PeterDaveHello** [comment]
@tianon thanks for your rapid help! (I didn't figure it out about how to make it working yet ha ...)

**Comment by tianon** [comment]
Just waiting on Travis to verify that it all builds properly -- then we'll merge.

Working on PHP now. :+1:

**Pull request merged**
